[build]
  base = "chess-client/"
  publish = "dist/"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_SOCKET_URL = "https://chess-d9hjfzchd4gug6a8.centralindia-01.azurewebsites.net/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200