[build]
  base = "chess-client/"
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_SOCKET_URL = "https://chessmatecom.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200