[build]
  base = "chess-client/"
  publish = "dist/"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_SOCKET_URL = "http://localhost:3000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200